CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'auth') THEN
            CREATE SCHEMA auth;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'evt') THEN
            CREATE SCHEMA evt;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'master') THEN
            CREATE SCHEMA master;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'moi') THEN
            CREATE SCHEMA moi;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'core') THEN
            CREATE SCHEMA core;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE auth.audit_logs (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer,
        principal_type integer,
        principal_id integer,
        action character varying(60) NOT NULL,
        entity_name character varying(60),
        entity_id character varying(40),
        details character varying(1000),
        ip_address character varying(50),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_audit_logs PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE master.denominations (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        value integer NOT NULL,
        is_coin boolean NOT NULL,
        is_active boolean NOT NULL,
        sort_order integer NOT NULL,
        CONSTRAINT pk_denominations PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE auth.notification_logs (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer,
        channel integer NOT NULL,
        recipient character varying(150) NOT NULL,
        subject character varying(200),
        body character varying(2000) NOT NULL,
        status integer NOT NULL,
        provider character varying(50),
        error character varying(1000),
        created_at timestamp with time zone NOT NULL,
        CONSTRAINT pk_notification_logs PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE auth.otp_requests (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        channel integer NOT NULL,
        destination character varying(150) NOT NULL,
        purpose integer NOT NULL,
        code_hash character varying(100) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        attempts integer NOT NULL,
        max_attempts integer NOT NULL,
        is_used boolean NOT NULL,
        used_at timestamp with time zone,
        ip_address character varying(50),
        CONSTRAINT pk_otp_requests PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE moi.persons (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        mobile character varying(15),
        initial character varying(12),
        name character varying(150) NOT NULL,
        name_ta character varying(150),
        spouse_initial character varying(12),
        spouse_name character varying(150),
        spouse_name_ta character varying(150),
        work character varying(100),
        city character varying(80),
        city_ta character varying(80),
        is_verified boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_persons PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE core.plans (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(60) NOT NULL,
        price_monthly numeric(12,2) NOT NULL,
        price_per_function numeric(12,2) NOT NULL,
        max_operators integer NOT NULL,
        max_functions_per_month integer NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_plans PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE auth.refresh_tokens (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        principal_type integer NOT NULL,
        principal_id integer NOT NULL,
        token_hash character varying(100) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        revoked_at timestamp with time zone,
        created_by_ip character varying(50),
        CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE auth.users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        full_name character varying(150) NOT NULL,
        full_name_ta character varying(150),
        email character varying(150),
        mobile character varying(15),
        password_hash character varying(100),
        user_type integer NOT NULL,
        is_active boolean NOT NULL,
        is_mobile_verified boolean NOT NULL,
        is_email_verified boolean NOT NULL,
        last_login_at timestamp with time zone,
        person_id integer,
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_users PRIMARY KEY (id),
        CONSTRAINT fk_users_persons_person_id FOREIGN KEY (person_id) REFERENCES moi.persons (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE core.tenants (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(12) NOT NULL,
        name character varying(150) NOT NULL,
        name_ta character varying(150),
        tagline character varying(200),
        owner_name character varying(150) NOT NULL,
        email character varying(150),
        mobile character varying(15) NOT NULL,
        alt_mobile character varying(15),
        address_line character varying(300),
        city character varying(80),
        district character varying(80),
        state character varying(80) NOT NULL,
        pincode character varying(10),
        gstin character varying(15),
        logo_path character varying(300),
        primary_color character varying(10),
        receipt_header character varying(300),
        receipt_footer character varying(300),
        status integer NOT NULL,
        plan_id integer,
        trial_ends_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_tenants PRIMARY KEY (id),
        CONSTRAINT fk_tenants_plans_plan_id FOREIGN KEY (plan_id) REFERENCES core.plans (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE master.expense_categories (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        tenant_id integer,
        name character varying(100) NOT NULL,
        name_ta character varying(100),
        sort_order integer NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT pk_expense_categories PRIMARY KEY (id),
        CONSTRAINT fk_expense_categories_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenants (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE master.function_types (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        tenant_id integer,
        name character varying(100) NOT NULL,
        name_ta character varying(100),
        sort_order integer NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT pk_function_types PRIMARY KEY (id),
        CONSTRAINT fk_function_types_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenants (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE master.gift_item_types (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        unit character varying(30),
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        tenant_id integer,
        name character varying(100) NOT NULL,
        name_ta character varying(100),
        sort_order integer NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT pk_gift_item_types PRIMARY KEY (id),
        CONSTRAINT fk_gift_item_types_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenants (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE master.moi_categories (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        is_highlighted boolean NOT NULL,
        color character varying(10),
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        tenant_id integer,
        name character varying(100) NOT NULL,
        name_ta character varying(100),
        sort_order integer NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT pk_moi_categories PRIMARY KEY (id),
        CONSTRAINT fk_moi_categories_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenants (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE core.operators (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        code character varying(12) NOT NULL,
        name character varying(150) NOT NULL,
        name_ta character varying(150),
        mobile character varying(15) NOT NULL,
        pin_hash character varying(100) NOT NULL,
        is_active boolean NOT NULL,
        last_login_at timestamp with time zone,
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_operators PRIMARY KEY (id),
        CONSTRAINT fk_operators_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenants (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE core.tenant_members (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        user_id integer NOT NULL,
        role integer NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_tenant_members PRIMARY KEY (id),
        CONSTRAINT fk_tenant_members_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenants (id) ON DELETE RESTRICT,
        CONSTRAINT fk_tenant_members_users_user_id FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE evt.functions (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        code character varying(8) NOT NULL,
        function_type_id integer NOT NULL,
        name character varying(200) NOT NULL,
        name_ta character varying(200),
        owner_name character varying(150) NOT NULL,
        owner_name_ta character varying(150),
        owner_mobile character varying(15) NOT NULL,
        owner_email character varying(150),
        location character varying(200) NOT NULL,
        location_ta character varying(200),
        address character varying(300),
        city character varying(80),
        function_date date NOT NULL,
        start_time time,
        end_time time,
        expected_guests integer,
        other_details character varying(1000),
        allow_cash boolean NOT NULL,
        allow_upi boolean NOT NULL,
        status integer NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_functions PRIMARY KEY (id),
        CONSTRAINT fk_functions_function_types_function_type_id FOREIGN KEY (function_type_id) REFERENCES master.function_types (id) ON DELETE RESTRICT,
        CONSTRAINT fk_functions_tenants_tenant_id FOREIGN KEY (tenant_id) REFERENCES core.tenants (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE evt.counters (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        function_id integer NOT NULL,
        number integer NOT NULL,
        name character varying(50) NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_counters PRIMARY KEY (id),
        CONSTRAINT fk_counters_functions_function_id FOREIGN KEY (function_id) REFERENCES evt.functions (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE moi.function_expenses (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        function_id integer NOT NULL,
        expense_category_id integer,
        taken_by_name character varying(150) NOT NULL,
        taken_by_name_ta character varying(150),
        relation character varying(80),
        taken_by_mobile character varying(15),
        purpose character varying(200) NOT NULL,
        amount numeric(14,2) NOT NULL,
        payment_mode integer NOT NULL,
        entry_at timestamp with time zone NOT NULL,
        operator_id integer,
        notes character varying(500),
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_function_expenses PRIMARY KEY (id),
        CONSTRAINT fk_function_expenses_expense_categories_expense_category_id FOREIGN KEY (expense_category_id) REFERENCES master.expense_categories (id) ON DELETE RESTRICT,
        CONSTRAINT fk_function_expenses_functions_function_id FOREIGN KEY (function_id) REFERENCES evt.functions (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE moi.moi_entries (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        function_id integer NOT NULL,
        counter_id integer,
        operator_id integer,
        person_id integer,
        serial_no integer NOT NULL,
        receipt_no character varying(40) NOT NULL,
        mobile character varying(15),
        initial character varying(12),
        name character varying(150) NOT NULL,
        name_ta character varying(150),
        spouse_initial character varying(12),
        spouse_name character varying(150),
        spouse_name_ta character varying(150),
        work character varying(100),
        city character varying(80),
        city_ta character varying(80),
        moi_category_id integer,
        is_highlighted boolean NOT NULL,
        amount numeric(14,2) NOT NULL,
        payment_mode integer NOT NULL,
        payment_ref character varying(60),
        notes character varying(500),
        status integer NOT NULL,
        reversal_reason character varying(300),
        entry_at timestamp with time zone NOT NULL,
        client_ref character varying(60),
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_moi_entries PRIMARY KEY (id),
        CONSTRAINT fk_moi_entries_counters_counter_id FOREIGN KEY (counter_id) REFERENCES evt.counters (id) ON DELETE RESTRICT,
        CONSTRAINT fk_moi_entries_functions_function_id FOREIGN KEY (function_id) REFERENCES evt.functions (id) ON DELETE RESTRICT,
        CONSTRAINT fk_moi_entries_moi_categories_moi_category_id FOREIGN KEY (moi_category_id) REFERENCES master.moi_categories (id) ON DELETE RESTRICT,
        CONSTRAINT fk_moi_entries_operators_operator_id FOREIGN KEY (operator_id) REFERENCES core.operators (id) ON DELETE RESTRICT,
        CONSTRAINT fk_moi_entries_persons_person_id FOREIGN KEY (person_id) REFERENCES moi.persons (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE evt.operator_assignments (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        tenant_id integer NOT NULL,
        function_id integer NOT NULL,
        counter_id integer NOT NULL,
        operator_id integer NOT NULL,
        valid_from timestamp without time zone NOT NULL,
        valid_to timestamp without time zone NOT NULL,
        is_active boolean NOT NULL,
        created_at timestamp with time zone NOT NULL,
        created_by integer,
        updated_at timestamp with time zone,
        updated_by integer,
        is_deleted boolean NOT NULL,
        CONSTRAINT pk_operator_assignments PRIMARY KEY (id),
        CONSTRAINT fk_operator_assignments_counters_counter_id FOREIGN KEY (counter_id) REFERENCES evt.counters (id) ON DELETE RESTRICT,
        CONSTRAINT fk_operator_assignments_functions_function_id FOREIGN KEY (function_id) REFERENCES evt.functions (id) ON DELETE RESTRICT,
        CONSTRAINT fk_operator_assignments_operators_operator_id FOREIGN KEY (operator_id) REFERENCES core.operators (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE moi.moi_entry_denominations (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        moi_entry_id integer NOT NULL,
        note_value integer NOT NULL,
        count integer NOT NULL,
        total numeric(14,2) NOT NULL,
        CONSTRAINT pk_moi_entry_denominations PRIMARY KEY (id),
        CONSTRAINT fk_moi_entry_denominations_moi_entries_moi_entry_id FOREIGN KEY (moi_entry_id) REFERENCES moi.moi_entries (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE TABLE moi.moi_entry_gifts (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        moi_entry_id integer NOT NULL,
        gift_item_type_id integer,
        description character varying(200) NOT NULL,
        description_ta character varying(200),
        quantity numeric(10,3) NOT NULL,
        estimated_value numeric(14,2),
        CONSTRAINT pk_moi_entry_gifts PRIMARY KEY (id),
        CONSTRAINT fk_moi_entry_gifts_gift_item_types_gift_item_type_id FOREIGN KEY (gift_item_type_id) REFERENCES master.gift_item_types (id) ON DELETE RESTRICT,
        CONSTRAINT fk_moi_entry_gifts_moi_entries_moi_entry_id FOREIGN KEY (moi_entry_id) REFERENCES moi.moi_entries (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_audit_logs_tenant_id_created_at ON auth.audit_logs (tenant_id, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_counters_function_id_number ON evt.counters (function_id, number);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE UNIQUE INDEX ix_denominations_value ON master.denominations (value);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_expense_categories_tenant_id_sort_order ON master.expense_categories (tenant_id, sort_order);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_function_expenses_expense_category_id ON moi.function_expenses (expense_category_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_function_expenses_function_id ON moi.function_expenses (function_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_function_types_tenant_id_sort_order ON master.function_types (tenant_id, sort_order);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE UNIQUE INDEX ix_functions_code ON evt.functions (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_functions_function_type_id ON evt.functions (function_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_functions_owner_mobile ON evt.functions (owner_mobile);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_functions_tenant_id_function_date ON evt.functions (tenant_id, function_date);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_gift_item_types_tenant_id_sort_order ON master.gift_item_types (tenant_id, sort_order);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_moi_categories_tenant_id_sort_order ON master.moi_categories (tenant_id, sort_order);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE UNIQUE INDEX ix_moi_entries_client_ref ON moi.moi_entries (client_ref) WHERE client_ref IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_moi_entries_counter_id ON moi.moi_entries (counter_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE UNIQUE INDEX ix_moi_entries_function_id_serial_no ON moi.moi_entries (function_id, serial_no);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_moi_entries_moi_category_id ON moi.moi_entries (moi_category_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_moi_entries_name_city ON moi.moi_entries (name, city);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_moi_entries_operator_id ON moi.moi_entries (operator_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_moi_entries_person_id ON moi.moi_entries (person_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_moi_entries_tenant_id_mobile ON moi.moi_entries (tenant_id, mobile);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_moi_entry_denominations_moi_entry_id ON moi.moi_entry_denominations (moi_entry_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_moi_entry_gifts_gift_item_type_id ON moi.moi_entry_gifts (gift_item_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_moi_entry_gifts_moi_entry_id ON moi.moi_entry_gifts (moi_entry_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_operator_assignments_counter_id ON evt.operator_assignments (counter_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_operator_assignments_function_id ON evt.operator_assignments (function_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_operator_assignments_operator_id_is_active ON evt.operator_assignments (operator_id, is_active);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE UNIQUE INDEX ix_operators_tenant_id_code ON core.operators (tenant_id, code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_otp_requests_destination_purpose_created_at ON auth.otp_requests (destination, purpose, created_at);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE UNIQUE INDEX ix_persons_mobile ON moi.persons (mobile) WHERE mobile IS NOT NULL AND is_deleted = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_refresh_tokens_principal_type_principal_id ON auth.refresh_tokens (principal_type, principal_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE UNIQUE INDEX ix_refresh_tokens_token_hash ON auth.refresh_tokens (token_hash);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE UNIQUE INDEX ix_tenant_members_tenant_id_user_id ON core.tenant_members (tenant_id, user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_tenant_members_user_id ON core.tenant_members (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE UNIQUE INDEX ix_tenants_code ON core.tenants (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_tenants_plan_id ON core.tenants (plan_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE UNIQUE INDEX ix_users_email ON auth.users (email) WHERE email IS NOT NULL AND is_deleted = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE UNIQUE INDEX ix_users_mobile_user_type ON auth.users (mobile, user_type) WHERE mobile IS NOT NULL AND is_deleted = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    CREATE INDEX ix_users_person_id ON auth.users (person_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261008072432_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20261008072432_InitialPostgres', '10.0.12');
    END IF;
END $EF$;
COMMIT;

